name: Test

on:
  pull_request:
    branches: [ master ]

jobs:	
  unit-tests:	
    name: Unit Tests	
    runs-on: ubuntu-latest	
    steps:	
      - uses: actions/checkout@v2	

      - name: install	
        run: yarn	

      - name: test	
        run: yarn test